// Customizer const
export const TOGGLE_COLLAPSED_NAV = 'TOGGLE_COLLAPSE_MENU';
export const WINDOW_WIDTH = 'WINDOW-WIDTH';
export const SWITCH_LANGUAGE = 'SWITCH-LANGUAGE';

//Contact Module const
export const FETCH_START = 'fetch_start';
export const FETCH_SUCCESS = 'fetch_success';
export const FETCH_ERROR = 'fetch_error';
export const SHOW_MESSAGE = 'SHOW_MESSAGE';
export const HIDE_MESSAGE = 'HIDE_MESSAGE';
export const ON_SHOW_LOADER = 'ON_SHOW_LOADER';
export const ON_HIDE_LOADER = 'ON_HIDE_LOADER';

//Auth const
export const SIGNUP_USER = 'SIGNUP_USER';
export const SIGNUP_USER_SUCCESS = 'SIGNUP_USER_SUCCESS';
export const SIGNIN_GOOGLE_USER = 'SIGNIN_GOOGLE_USER';
export const SIGNIN_GOOGLE_USER_SUCCESS = 'SIGNIN_GOOGLE_USER_SUCCESS';
export const SIGNIN_FACEBOOK_USER = 'SIGNIN_FACEBOOK_USER';
export const SIGNIN_FACEBOOK_USER_SUCCESS = 'SIGNIN_FACEBOOK_USER_SUCCESS';
export const SIGNIN_TWITTER_USER = 'SIGNIN_TWITTER_USER';
export const SIGNIN_TWITTER_USER_SUCCESS = 'SIGNIN_TWITTER_USER_SUCCESS';
export const SIGNIN_GITHUB_USER = 'SIGNIN_GITHUB_USER';
export const SIGNIN_GITHUB_USER_SUCCESS = 'signin_github_user_success';
export const SIGNIN_USER = 'SIGNIN_USER';
export const SIGNIN_USER_SUCCESS = 'SIGNIN_USER_SUCCESS';
export const SIGNOUT_USER = 'SIGNOUT_USER';
export const SIGNOUT_USER_SUCCESS = 'SIGNOUT_USER_SUCCESS';
export const INIT_URL = 'INIT_URL';
export const FORGOT_PASSWORD_REQUEST = 'FORGOT_PASSWORD_REQUEST';
export const FORGOT_PASSWORD_REQUEST_SUCCESS = 'FORGOT_PASSWORD_REQUEST_SUCCESS';
export const RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST';
export const RESET_PASSWORD_REQUEST_SUCCESS = 'RESET_PASSWORD_REQUEST_SUCCESS';
export const CHANGE_PASSWORD_REQUEST = 'CHANGE_PASSWORD_REQUEST';
export const CHANGE_PASSWORD_REQUEST_SUCCESS = 'CHANGE_PASSWORD_REQUEST_SUCCESS';
export const DEVICE_REQUEST = 'DEVICE_REQUEST';
export const DEVICE_REQUEST_SUCCESS = 'DEVICE_REQUEST_SUCCESS';
export const VERIFICATION_REQUEST = 'VERIFICATION_REQUEST';
export const VERIFICATION_REQUEST_SUCCESS = 'VERIFICATION_REQUEST_SUCCESS';
export const PROFILE_READ_REQUEST = 'PROFILE_READ_REQUEST';
export const PROFILE_READ_REQUEST_SUCCESS = 'PROFILE_READ_REQUEST_SUCCESS';
export const PROFILE_UPDATE_REQUEST = 'PROFILE_UPDATE_REQUEST';
export const PROFILE_UPDATE_REQUEST_SUCCESS = 'PROFILE_UPDATE_REQUEST_SUCCESS';

//Sticky
export const GET_STICKY = 'GET_STICKY';
export const NOTES_UPDATE = 'NOTES_UPDATE';
export const FETCH_ALL_NOTES_SUCCESS = 'FETCH_ALL_NOTES_SUCCESS';
export const UPDATE_ALL_NOTES_SUCCESS = 'UPDATE_ALL_NOTES_SUCCESS';

//Contact
export const GET_All_CONTACT_SUCCESS = 'GET_All_CONTACT_SUCCESS';
export const ON_ADD_CONTACT_SUCCESS = 'ON_ADD_CONTACT_SUCCESS';
export const UPDATE_CONTACT_SUCCESS = 'UPDATE_CONTACT_SUCCESS';
export const DELETE_CONTACT_SUCCESS = 'DELETE_CONTACT_SUCCESS';

//Security Question

export const GET_ALL_SECURITY_QUESTION = 'GET_ALL_SECURITY_QUESTION';
export const GET_ALL_SECURITY_QUESTION_SUCCESS = 'GET_ALL_SECURITY_QUESTION_SUCCESS';
export const SAVE_SECURITY_QUESTION_ANSWER = 'SAVE_SECURITY_QUESTION_ANSWER';
export const SAVE_SECURITY_QUESTION_ANSWER_SUCCESS = 'SAVE_SECURITY_QUESTION_ANSWER_SUCCESS'

//common 

export const GET_DATA = 'GET_DATA';
export const GET_DATA_ONE = 'GET_DATA_ONE';
export const ADD_DATA = 'ADD_DATA';
export const UPDATE_DATA = 'UPDATE_DATA';
export const DELETE_DATA = 'DELETE_DATA';
export const GET_DATA_SUCCESS = 'GET_DATA_SUCCESS';
export const GET_DATA_ONE_SUCCESS = 'GET_DATA_ONE_SUCCESS';
export const ADD_DATA_SUCCESS = 'ADD_DATA_SUCCESS';
export const UPDATE_DATA_SUCCESS = 'UPDATE_DATA_SUCCESS';
export const DELETE_DATA_SUCCESS = 'DELETE_DATA_SUCCESS';
export const SECTOR_GET_DATA = 'SECTOR_GET_DATA';
export const SECTOR_GET_DATA_SUCCESS = 'SECTOR_GET_DATA_SUCCESS';
export const SECTOR_DELETE_DATA = 'SECTOR_DELETE_DATA';
export const BROKER_GET_DATA = 'BROKER_GET_DATA';
export const BROKER_GET_DATA_SUCCESS = 'BROKER_GET_DATA_SUCCESS';
export const BROKER_DELETE_DATA = 'BROKER_DELETE_DATA';
export const BROKER_DELETE_DATA_SUCCESS = 'BROKER_DELETE_DATA_SUCCESS';
export const BROKER_ADD_DATA = 'BROKER_ADD_DATA';
export const BROKER_ADD_DATA_SUCCESS = 'BROKER_ADD_DATA_SUCCESS';
export const BROKER_UPDATE_DATA = 'BROKER_UPDATE_DATA';
export const BROKER_UPDATE_DATA_SUCCESS = 'BROKER_UPDATE_DATA_SUCCESS';

// test 
export const USER_DATA_STORAGE = 'USER_DATA_STORAGE';